import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Btn, Empty, Icon, Status } from '@/components/ui'
import { proxiedPlanUrl } from '@/lib/agentClient'

/**
 * Plan pages are built by the TripAgent backend as one self-contained HTML file,
 * with their own stylesheet. We show them intact in a sandboxed frame rather than
 * re-rendering their content in the app's design language — the page is the
 * artefact the member keeps and forwards, and rewriting it here would mean two
 * versions of the same plan that could drift apart.
 *
 * The chrome around the frame is Nocturne; the page inside is the document.
 */
export default function PlanPage() {
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const [html, setHtml] = useState<string | null>(null)
  const [failed, setFailed] = useState(false)

  const raw = params.get('u') ?? ''
  const src = useMemo(() => (raw ? proxiedPlanUrl(raw) : ''), [raw])

  /**
   * The page is fetched and handed to the frame as srcdoc rather than pointed at
   * with src. Both render the same self-contained document, but fetching keeps the
   * request on the app's own origin — some embedded contexts refuse to let a frame
   * make its own network call — and it lets us show a real error instead of a
   * silently blank frame.
   */
  useEffect(() => {
    if (!src) return
    let cancelled = false
    setHtml(null)
    setFailed(false)
    fetch(src, { signal: AbortSignal.timeout(15_000) })
      .then((res) => {
        if (!res.ok) throw new Error(String(res.status))
        return res.text()
      })
      .then((text) => {
        if (!cancelled) setHtml(text)
      })
      .catch(() => {
        if (!cancelled) setFailed(true)
      })
    return () => {
      cancelled = true
    }
  }, [src])

  if (!src) {
    return (
      <div className="mx-auto min-h-full w-full max-w-app" style={{ background: 'var(--ink-0)' }}>
        <Empty
          icon="document"
          title="No plan to open."
          body="Ask Tara to build an itinerary and the page will open here."
          action={
            <Btn tone="primary" icon="horizon" onClick={() => navigate('/concierge')}>
              Tara
            </Btn>
          }
        />
      </div>
    )
  }

  return (
    <div className="mx-auto flex h-full w-full max-w-app flex-col" style={{ background: 'var(--ink-0)' }}>
      <div
        className="flex shrink-0 items-center gap-3 px-4 py-3"
        style={{ borderBottom: '1px solid var(--line)', paddingTop: 'max(12px, calc(env(safe-area-inset-top) + 8px))' }}
      >
        <button
          type="button"
          aria-label="Back"
          className="k-icon-btn k-icon-btn-solid"
          onClick={() => navigate('/journeys')}
        >
          <Icon name="back" size={20} />
        </button>
        <div className="min-w-0 flex-1">
          <p className="t-title-s">Your plan</p>
          <p className="t-caption t-mono truncate c-ivory-3">{raw}</p>
        </div>
        <a
          href={src}
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Open the plan in a new tab"
          className="k-icon-btn k-icon-btn-solid"
        >
          <Icon name="arrow-up-right" size={18} />
        </a>
      </div>

      {failed ? (
        <Empty
          icon="link"
          title="That page did not load."
          body="The link may have moved on since the plan was built. Open your itinerary in Journeys, or ask the Desk to send the page again."
          action={
            <Btn tone="ghost" icon="route" onClick={() => navigate('/journeys')}>
              Go to Journeys
            </Btn>
          }
        />
      ) : html === null ? (
        <div className="flex min-h-0 flex-1 items-center justify-center">
          <p className="t-caption">Opening your plan…</p>
        </div>
      ) : (
        <iframe
          srcDoc={html}
          title="Trip plan"
          // Generated by our own backend, but it carries researched third-party
          // content; keep it sandboxed and let it run only its own scripts.
          sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox"
          referrerPolicy="no-referrer"
          className="min-h-0 w-full flex-1 border-0"
          style={{ background: 'var(--paper)' }}
        />
      )}

      <div
        className="flex shrink-0 items-center justify-between gap-3 px-4 py-3"
        style={{ borderTop: '1px solid var(--line)', paddingBottom: 'max(12px, env(safe-area-inset-bottom))' }}
      >
        <Status tone="progress">
          <Icon name="lock" size={12} /> Served from the Desk
        </Status>
        <button type="button" className="k-link" onClick={() => navigate('/concierge')}>
          Refine with Tara
          <Icon name="forward" size={16} />
        </button>
      </div>
    </div>
  )
}
