import type { ImageMap } from './types'

/**
 * The onboarding photographs, served from our own origin.
 *
 * Chosen by hand from Wikimedia Commons under open licences, so they cost
 * nothing per member and never depend on a quota. Each carries its
 * photographer's credit, shown on the picture as the licence asks.
 */
export const ONBOARDING_IMAGES: ImageMap = {
  'passion:food': '/img/onboarding/passion-food.jpg',
  'passion:adrenaline': '/img/onboarding/passion-adrenaline.jpg',
  'passion:nightlife': '/img/onboarding/passion-nightlife.jpg',
  'passion:wellness': '/img/onboarding/passion-wellness.jpg',
  'passion:art': '/img/onboarding/passion-art.jpg',
  'passion:shopping': '/img/onboarding/passion-shopping.jpg',
  'passion:sport': '/img/onboarding/passion-sport.jpg',
  'passion:slow': '/img/onboarding/passion-slow.jpg',
  'house:aman': '/img/onboarding/house-aman.jpg',
  'house:chevalblanc': '/img/onboarding/house-chevalblanc.jpg',
  'house:fourseasons': '/img/onboarding/house-fourseasons.jpg',
  'house:rosewood': '/img/onboarding/house-rosewood.jpg',
  'house:belmond': '/img/onboarding/house-belmond.jpg',
  'house:sixsenses': '/img/onboarding/house-sixsenses.jpg',
  'house:soneva': '/img/onboarding/house-soneva.jpg',
  'house:oberoi': '/img/onboarding/house-oberoi.jpg',
  'house:taj': '/img/onboarding/house-taj.jpg',
  'house:mandarin': '/img/onboarding/house-mandarin.jpg',
  'house:raffles': '/img/onboarding/house-raffles.jpg',
  'house:bulgari': '/img/onboarding/house-bulgari.jpg',
  'place:maldives': '/img/onboarding/place-maldives.jpg',
  'place:amalfi': '/img/onboarding/place-amalfi.jpg',
  'place:kyoto': '/img/onboarding/place-kyoto.jpg',
  'place:heliski': '/img/onboarding/place-heliski.jpg',
  'place:nyc': '/img/onboarding/place-nyc.jpg',
  'place:dubai': '/img/onboarding/place-dubai.jpg',
  'place:mara': '/img/onboarding/place-mara.jpg',
  'place:ranthambore': '/img/onboarding/place-ranthambore.jpg',
  'place:antarctica': '/img/onboarding/place-antarctica.jpg',
  'place:iceland': '/img/onboarding/place-iceland.jpg',
  'place:alula': '/img/onboarding/place-alula.jpg',
  'place:udaipur': '/img/onboarding/place-udaipur.jpg',
  'place:bhutan': '/img/onboarding/place-bhutan.jpg',
  'place:tuscany': '/img/onboarding/place-tuscany.jpg',
  'place:stmoritz': '/img/onboarding/place-stmoritz.jpg',
  'place:riviera': '/img/onboarding/place-riviera.jpg',
  'place:borabora': '/img/onboarding/place-borabora.jpg',
  'place:tokyo': '/img/onboarding/place-tokyo.jpg',
  'place:fjords': '/img/onboarding/place-fjords.jpg',
  'place:rwanda': '/img/onboarding/place-rwanda.jpg',
  'place:paris': '/img/onboarding/place-paris.jpg',
  'place:milan': '/img/onboarding/place-milan.jpg',
  'place:mykonos': '/img/onboarding/place-mykonos.jpg',
  'place:standrews': '/img/onboarding/place-standrews.jpg',
  'place:seychelles': '/img/onboarding/place-seychelles.jpg',
  'place:patagonia': '/img/onboarding/place-patagonia.jpg',
  'place:galapagos': '/img/onboarding/place-galapagos.jpg',
}

export const ONBOARDING_CREDITS: ImageMap = {
  'passion:food': 'Wikimedia Commons · CC BY-SA 3.0',
  'passion:adrenaline': 'Jankenhoi · CC BY-SA 3.0',
  'passion:nightlife': 'PattayaPatrol · CC BY-SA 4.0',
  'passion:wellness': 'Brocken Inaglory · CC BY-SA 3.0',
  'passion:art': 'Saschaporsche · CC BY-SA 4.0',
  'passion:shopping': 'C messier · CC BY-SA 4.0',
  'passion:sport': 'WilliamFMeyer · CC BY-SA 4.0',
  'passion:slow': 'Martin Falbisoner · CC BY-SA 4.0',
  'house:aman': 'Steve Jurvetson · CC BY 2.0',
  'house:chevalblanc': 'Martin Falbisoner · CC BY-SA 4.0',
  'house:fourseasons': 'Didierlefort · CC BY-SA 3.0',
  'house:rosewood': 'Wpcpey · CC BY-SA 4.0',
  'house:belmond': 'JiriMatejicek · CC BY-SA 3.0',
  'house:sixsenses': 'Charles J. Sharp · CC BY-SA 4.0',
  'house:soneva': 'josef knecht · CC BY 3.0',
  'house:oberoi': 'McKay Savage from London, UK · CC BY 2.0',
  'house:taj': 'Navneet Sharma · CC BY-SA 4.0',
  'house:mandarin': 'This Photo was taken by Supanut Arunoprayote. Feel free to · CC BY 4.0',
  'house:raffles': 'Diego Delso · CC BY-SA 4.0',
  'house:bulgari': 'Simon_sees · CC BY 2.0',
  'place:maldives': 'Martin Falbisoner · CC BY-SA 4.0',
  'place:amalfi': 'Alexis Lours · CC BY 4.0',
  'place:kyoto': 'Martin Falbisoner · CC BY-SA 4.0',
  'place:heliski': 'This Photo was taken by Timothy A. Gonsalves. Feel free to · CC BY-SA 4.0',
  'place:nyc': 'King of Hearts · CC BY-SA 4.0',
  'place:dubai': 'Laika ac · CC BY-SA 2.0',
  'place:mara': 'Volodymyr Burdiak · CC BY-SA 4.0',
  'place:ranthambore': 'Rohit Sharma · CC BY-SA 4.0',
  'place:antarctica': 'Virtual-Pano · CC BY-SA 4.0',
  'place:iceland': 'Giles Laurent · CC BY-SA 4.0',
  'place:alula': 'CEphoto, Uwe Aranas · CC BY-SA 3.0',
  'place:udaipur': 'Navneet Sharma · CC BY-SA 4.0',
  'place:bhutan': 'Bernard Gagnon · CC BY-SA 4.0',
  'place:tuscany': 'JP Vets · CC BY-SA 4.0',
  'place:stmoritz': 'Murdockcrc · CC BY 3.0',
  'place:riviera': 'Martin St-Amant (S23678) · CC BY-SA 3.0',
  'place:borabora': 'Petar Milošević · CC BY-SA 4.0',
  'place:tokyo': 'Marek Ślusarczyk (Tupungato) Photo portfolio · CC BY 3.0',
  'place:fjords': 'Ximonic (Simo Räsänen) · CC BY-SA 3.0',
  'place:rwanda': 'Charles J. Sharp · CC BY-SA 4.0',
  'place:paris': 'Tristan Nitot · CC BY-SA 3.0',
  'place:milan': 'FlavMi · CC BY-SA 3.0',
  'place:mykonos': 'Roberto Faccenda · CC BY-SA 2.0',
  'place:standrews': 'Optograph · CC BY-SA 3.0',
  'place:seychelles': 'Tobias Alt, Tobi 87 · CC BY-SA 4.0',
  'place:patagonia': 'Pedro Szekely from Los Angeles, USA · CC BY-SA 2.0',
  'place:galapagos': 'Diego Delso · CC BY-SA 4.0',
}
